### ISSUE TITLE
Make image component responsive

### ISSUE THREAD

**Issue by blerchin** [blerchin/dma-20-mfa-show#22]
https://github.com/blerchin/dma-20-mfa-show/issues/9#issuecomment-629976186

Due to varying needs of users on different devices, we should serve several sizes of images via `srcset`. This requires converting artist images to several different versions. This can be created either through a script that converts images in the repo to different versions, or by using [`webpack-responsive-loader`](https://github.com/dscafati/responsive-loader).

**Comment by hsab** [comment]
fixed this in the [artist-pages](https://github.com/blerchin/dma-20-mfa-show/tree/artist-pages) https://github.com/blerchin/dma-20-mfa-show/commit/5e310f075f9c561c5e01a25a6ae176d270d88f9f
make sure to rerun `npm install`

**Comment by brysonian** [comment]
Out of curiosity, why the background image vs object-fit? Also @blerchin is there a preference for objects or hooks?

**Comment by blerchin** [comment]
I am also curious about the background image.
I prefer hooks in most cases. This looks like a case where it would be easy to switch. Occasionally for complex components the class style works better. That said, I realize there is a learning curve so I'm not going to be pedantic about it.

**Comment by blerchin** [comment]
@hsab I think it would be preferable to have this as a separate PR so we can discuss the implementation aside from lauren's work on the pages

**Comment by hsab** [comment]
@brysonian This is the first time I'm hearing about object-fit. 
But just to explain my train of thought: the module creates a placeholder image, a resized version @50x50px. I basically set the bg image to this placeholder until the actual image is loaded. Once loaded I remove the bg image. Removal is so that transparent images don't have the 2 images overlayed, it was making this blurry edge artifact on Grahams photos. 

I was thinking of using the placeholder as the src of the img. But then high def one won't get loaded unless I have 2 img tags that are toggled for display. 

@blerchin  I have no idea about hooks etc. Just catching up with this react stuff. 

Also created a new branch [responsive-loader](https://github.com/blerchin/dma-20-mfa-show/tree/responive-loader)

**Comment by hsab** [comment]
@blerchin I was looking at hooks. And it seems like that's actually what I'm using. Sorry for my react illiteracy but can you send me some links to clarify "This looks like a case where it would be easy to switch (to hooks or something else?). Occasionally for complex components the **class style** works better."

**Comment by brysonian** [comment]
I can rewrite it as hooks if you are curious, but it is fine like this. Also i didn't mean the questions to be challenging, just trying to learn from y'all too.

**Comment by blerchin** [comment]
All good, it is a relatively new feature so a lot of sample code is implemented in the old style.
Basically react components can be functions or classes. It used to be the case that you could only use features like state, refs, and callbacks if you wrote your component as a class. Hooks allows you to use all these features from a function-style component. Due to the way it's implemented it prevents a lot of common bugs. And IMO it's prettier.

https://reactjs.org/docs/hooks-intro.html

**Comment by blerchin** [comment]
btw I did some device spot-testing and the responsive-loader stuff seems to be working great. So remaining qualms are just nitpicks :)

**Comment by hsab** [comment]
@brysonian no challenge at all. it was appropriate. I'm just gluing things together so the question is actually much appreciated to ensure code sanity. I'll take it as a challenge to rewrite in class-less hook style.

@ben makes sense ;) For now I'm assuming hooks = objects with react class features

**Comment by blerchin** [comment]
@hsab not sure what you mean by objects with react class features
I mean, technically a function is an object because javascript but I don't think that's what you mean =P

Sniff test would be... do you write
```
class MyComponent extends React.Component {
```
or
```
const MyComponent = (props) => {
```
at the beginning.

With the latter if you wanna use state it will have to be with hooks.

**Comment by brysonian** [comment]
this is a quick stab at the image using hooks. (note this has only been run in my head, without a linter, so there might be things i missed) https://gist.github.com/brysonian/d688cbc6e7da55340d5681cc3c873ee9

**Comment by hsab** [comment]
@blerchin `technically a function is an object because javascript` that's what I meant ;)

@brysonian https://github.com/blerchin/dma-20-mfa-show/commit/09f2666c2bfd9ec2cb3f5eef3b764227f74bdf23 I basically copy pasted your initial Image component and added the hook. Two questions...

~~Is there is difference between `const [showBG, setShowBG] = **useState**(true);` and `const [showBg, setShowBg] = **setState**(true);` for initialization?~~ [Found it](https://stackoverflow.com/a/53584591/2276356)

Also I tried `onLoad={setShowBG(false)}` and I kept getting a stack overflow with re-renders. Does this have to do with the scope of `this` and how it refers to the object's instance in arrow functions? Some internal react miss-referencing to prototype vs reference? 

:heart:

**Comment by blerchin** [comment]
`setState` is not a thing in hooks. you only use the setter that gets output by `useState`

the stack overflow is because you've created an infinite loop.
That callback is getting called every the render function gets called. Then setShowBg triggers a new render because it changed state.

generally you want to use a closure there that will call `setShowBG`. That's what `() => setShowBg(false)` does.
It doesn't actually have to do with the this context (though I can see why you'd think that). It has to do with when `setShowBg` gets called.

**Comment by hsab** [comment]
Right I asked bc of [this line](https://gist.github.com/brysonian/d688cbc6e7da55340d5681cc3c873ee9#file-image-js-L19) in the gist. I'm using `useState` in the code, based on the react intro link you sent earlier. 

Yeah the overflow makes sense as to how but not why. I'm just trying to understand why. `setShowBG` changes the state, that's a given. I'm trying to wrap my head around why it behaves differently in the closure vs calling it plainly. When in closure, it certainly changes the state of the component's _instance_. When called plainly as in `onLoad={setShowBG(false)}` it changes the state of ____? Component's prototype maybe?

Also on another note, how do you debug react so you can actually step through the code and see the stack? Tips would be much appreciated.

**Comment by blerchin** [comment]
If you wanna hop on a call for a couple mins I could probably explain this stuff faster that way

**Comment by brysonian** [comment]
ahh sorry, i knew i'd blow it somehow! 

When you do: onLoad={setShowBG(false)} it actually runs setShowBg() when the component mounts, which sets the bg, which triggers a re-render, which does the same thing etc. Also we can chat on slack if you like, or a telegram etc.
