### ISSUE TITLE
Gather requirements and mockup for each artist page

### ISSUE THREAD

**Issue by blerchin** [blerchin/dma-20-mfa-show#3]
Artist pages will be some configuration of these elements. If artists do not submit a mockup, any images and text submitted will be arranged according to the judgment of the designers.

![project-page-wireframe-01](https://user-images.githubusercontent.com/1322328/81344813-5418ca80-906c-11ea-8d3f-59d1f9789484.png)

**Comment by lmccart** [comment]
@blerchin @dalena What do you think about us just laying out a best guess for each person based on content and then asking them to review and request adjustments? I'm wondering if asking each person to make a mockup might just hold up responses because it feels like a bigger task. It's relatively trivial to switch from one column to two, etc. And it might be easier to make those decisions after seeing it on the page.

**Comment by lmccart** [comment]
I made a quick draft of a form to collect content here:
https://docs.google.com/forms/d/1UTFRaXHlM4621jp3B1w3MPCy6FlBkz16cTZZ-dC0Jew/edit

I'll also share with you all so you can edit directly. If someone else had another solution in mind for gathering content, we can scrap this. Just wanted to get something simple started if there was no other plan in action.

**Comment by dalena** [comment]
@lmccart I think this is a good call. There are several people who still haven't responded with mockups. However, some people have sent me their layout ideas already. So you'll receive them in an AI file, that should also help!

**Comment by dalena** [comment]
This form is great. Thank you for doing that Lauren. I will send this to the group now
