### ISSUE TITLE
Framerate very low on iPhone 6s

### ISSUE THREAD

**Issue by mileshiroo** [blerchin/dma-20-mfa-show#83]
Hello all,

The framerate is very low on my device, iPhone 6s. It seems to be just for the simulation / blob part, and not the other elements of the website. Not sure what's causing it but just wanted everyone to be aware that this is how the site might perform on slightly older devices.

Here is a screen recording that shows it:

https://www.youtube.com/watch?v=YeQSDl239E0

Miles

**Comment by hsab** [comment]
Can you test with this?
https://hsab.github.io/dma20-paper-test/blobs.html

**Comment by hsab** [comment]
I have a suspicion that this is react related,  even on desktop there is a noticeable performance drop.

**Comment by mileshiroo** [comment]
Yeah, that version is much more performant on my phone

**Comment by blerchin** [comment]
@mileshiroo can you try this version https://deploy-preview-70--kind-tesla-a088c1.netlify.app/
it's from before we added the labels on mobile. Wondering if that is affecting performance.

**Comment by mileshiroo** [comment]
@blerchin this is how it looks, it might be a little better but the transition where the blobs fall down is still pretty slow: 

https://www.youtube.com/watch?v=_ci8gjmOwhI

**Comment by mileshiroo** [comment]
just a suggestion, but if it's not possible to improve the framerate would it be possible to disable the falling down transition if the framerate is detected to be below a certain threshold, and just have the blobs instantly go to the bar on the bottom when you click them? the low framerate is mainly an issue when the blobs obstruct the project page and home/info during the transition

**Comment by blerchin** [comment]
Based on what I can tell from profiling this, the framerate is pretty good when React is not doing anything. In the simulator I'm running for 6s, I see about 50-60ms script execution per frame when React is doing nothing in the background, which is consistent with the paper demo. However when react is loading, or when we are shrinking the blobs, this drops to 120+ms per frame.
I think miles' solution is smart, I am not exactly sure how to determine which devices to use it on... Could be we just turn off the transition for small screens? Or do some timing on FPS to decide

**Comment by hsab** [comment]
I think fps profiling is a good option, especially for lower end devices in general. Although I could see unforeseeable bugs happening with this, we could def give it a try.

**Comment by hsab** [comment]
@blerchin just had a look, blobs implementation makes it really easy to have immediate resizing.
Created a new branch [`blobs-immresize`](https://github.com/blerchin/dma-20-mfa-show/tree/blobs-immresize). This add `this.immediateResize = true;` to the blobs.If the hardware is capable supports, the value should be set to `true`, otherwise `false`.

https://github.com/blerchin/dma-20-mfa-show/blob/98a31b175e1e08a21e05b2103854da9bc3907117/src/BlobField/blobs.js#L29

https://github.com/blerchin/dma-20-mfa-show/blob/98a31b175e1e08a21e05b2103854da9bc3907117/src/BlobField/blobs.js#L190-L197

I was hoping if you could handle the fps checking since I probably won't make the best choices when it comes to implementing this in react. I could however go ahead and have a look at it inside of blobs.js. Your call, let me know

**Comment by blerchin** [comment]
@hsab looks good. I can take a stab at the fps calculation. I don't think we actually want to involve react in that calculation. I was thinking of doing a wall clock count with a bit of averaging in the `onFrame` function, as this is what appears to run slowly.

**Comment by hsab** [comment]
Also think perhaps we should have immediateResize set to true by default? Profiling should perhaps disable it rather than enabling.

**Comment by blerchin** [comment]
closed by #86
